### ISSUE TITLE
ansible-navigator config just clears screen and returns blank

### ISSUE THREAD

**Issue by ffirg** [ansible/ansible-navigator#105]
ProductName:	macOS
ProductVersion:	11.2.1
BuildVersion:	20D74

Python 3.9.2
ansible-navigator 0.6.0

same when running :config within the TUI

**Comment by relrod** [comment]
Which ansible/ansible-core/ansible base version is installed and how was it installed?
Is `ansible-config` available in your $PATH and does it work?

I'm not able to reproduce this on macOS 11.2.3, py38.

**Comment by ffirg** [comment]
well it's working now!

pip list
ansible           3.2.0
ansible-base      2.10.7
ansible-navigator 0.6.0
ansible-runner    2.0.0a1
