### ISSUE TITLE
navigator config doesn't accept `~`

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#1273]
https://twitter.com/MetaSpoil/status/1559224334320914433

Needs to be verified, should be small fix

**Comment by ssbarnea** [comment]
@shatakshiiii If you can take care of this it would be awesome. You need to ensure that we call `expanduser()` on config items that can be paths.

@cidrblock One thing that I am not sure about is the meaning of `~` for destination. I am not sure if @tombosmansibm is aware of the fact that the expansion happens from the point of view of your current machine and not of the container.

If I remember correctly the user home on EE is running with `/runner` home and I am not aware of an easy way to determine this. Also hardcoding the expansion for dest from `~` to `/runner` seems like a hack that I would want to avoid.

**Comment by cidrblock** [comment]
@ssbarnea Yeah, it will need to be resolved on the host, so a FAQ entry might be good to eliminate any confusion about using `~` in the dest (probably even discouraged)

@shatakshiiii This func exists https://github.com/ansible/ansible-navigator/blob/main/src/ansible_navigator/utils/functions.py#L51 so we can probably just add using it in the volume mount post processor

**Comment by cidrblock** [comment]
Resolved by #1319
