### ISSUE TITLE
Ansible-navigator | ModuleNotFoundError: No module named '_curses'

### ISSUE THREAD

**Issue by Prabhakar-cg** [ansible/ansible-navigator#1321]
##### ISSUE TYPE

- Bug Report

##### SUMMARY

Ansible-navigator failed to initiate after installing via pip3. I am using Python3.10.8 as a base for ansible.
whenever i try to start ansible-navigator or just check version it gives following error 

##### ANSIBLE-NAVIGATOR VERSION
ansible-navigator-2.2.0
python version - 3.10.8

```
**(ansible) [vagrant@ansiclient opt]$ ansible-navigator
Traceback (most recent call last):
  File "/opt/ansible/bin/ansible-navigator", line 5, in <module>
    from ansible_navigator.cli import main
  File "/opt/ansible/lib/python3.10/site-packages/ansible_navigator/cli.py", line 11, in <module>
    from curses import wrapper
  File "/usr/local/lib/python3.10/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'**
```

##### STEPS TO REPRODUCE

 Base OS centos-7.9
 Python-3.10.8
 pip3.10 install ansible-navigator
 ansible-navigator -version

##### EXPECTED RESULTS

get ansible-navigator console

##### ACTUAL RESULTS

vagrant@ansiclient opt]$ ansible-navigator --version
Traceback (most recent call last):
  File "/opt/ansible/bin/ansible-navigator", line 5, in <module>
    from ansible_navigator.cli import main
  File "/opt/ansible/lib/python3.10/site-packages/ansible_navigator/cli.py", line 11, in <module>
    from curses import wrapper
  File "/usr/local/lib/python3.10/curses/__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

##### ADDITIONAL INFORMATION

![image](https://user-images.githubusercontent.com/25166774/197062249-1aac0a73-4ef4-4449-b219-ba4a4a724856.png)

**Comment by cidrblock** [comment]
@Prabhakar-cg thank for the issue!

I've only seen this one other time and it was when the python distribution on the system was not built with curses support.  One quick way to test this is from the python cli:

```
x1 ➜  ~ python
Python 3.10.7 (main, Sep  7 2022, 00:00:00) [GCC 12.2.1 20220819 (Red Hat 12.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
>>> 
```
Could you try that out and let us know what you see?

**Comment by Prabhakar-cg** [comment]
@cidrblock thanks for writing back on this. Seems the import function is not so straight forward for Linux, so I had to install ncurse  & sqlite-devel Linux binaries and then recompile the python from source code & install again. Seems i need to get my hands dirty on python.
However ansible-navigator started working after sorting those dependencies.

**Comment by cidrblock** [comment]
Great to hear, glad it got sorted.  Enjoy navigator and looking forward to any feedback.
