### ISSUE TITLE
"Node.js 12 actions are deprecated" after making pull request on docs

### ISSUE THREAD

**Issue by jdandrea** [ansible/ansible-navigator#1324]
I made two relatively minor changes to the docs and issued a pull request. Soon after, I received this error. Does something need to be updated in the ack workflow run? Unsure if I can do that or if someone else must tackle that one.

```
[ack / labels](https://github.com/ansible/ansible-navigator/actions/runs/3314504851/jobs/5473878965)
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. 
Please update the following actions to use Node.js 16: actions/checkout, actions/checkout
```

**Comment by cidrblock** [comment]
Thanks, it looks like we missed a configuration section for the dependabot configuration, the hope is that it picks up the outdated action and does a PR.

**Comment by cidrblock** [comment]
Related: #1326 
Related: #1327 

Cool.
