### ISSUE TITLE
ansible-navigator run can't directly access a playbook provided by a collection

### ISSUE THREAD

**Issue by zjpeterson** [ansible/ansible-navigator#1385]
##### ISSUE TYPE

- Bug Report

##### SUMMARY

`ansible-playbook` is able to [directly access a playbook](https://docs.ansible.com/ansible/latest/collections_guide/collections_using_playbooks.html#using-a-playbook-from-a-collection) provided by a collection. Trying to do the same thing with `ansible-navigator run` results in the tool trying to resolve it as a filename.

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 2.2.0
```

##### STEPS TO REPRODUCE

- Create a collection with a playbook located in the `playbooks/` directory
- Try to run `ansible-navigator run namespace.collection.playbook_name --eei container-with-collection-installed`

##### EXPECTED RESULTS

Playbook runs

##### ACTUAL RESULTS

Fully-qualified playbook name gets parsed as though it were a file and an error like the following is returned:
```
ERROR! the playbook: /working/dir/namespace.collection.playbook_name could not be found
```

##### ADDITIONAL INFORMATION

Running `ansible-playbook namespace.collection.playbook_name` does succeed with the collection installed locally, so this is something Ansible is supposed to be able to do.

Can be worked around by creating and running a one-line playbook like the following
```
- import_playbook: namespace.collection.playbook_name
```

**Comment by cidrblock** [comment]
Thanks for this! We'll look into it and post back with findings
