### ISSUE TITLE
Identify default execution environment config 

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible-navigator#141]
Currently, the default config is set to 
```
    "ansible-navigator": {
        "container-engine": "podman",
        "execution-environment": True,
        "execution-environment-image": "quay.io/ansible/ansible-runner:devel",
```
Refer https://github.com/ansible/ansible-navigator/blob/main/ansible_navigator/config.py#L32

**Comment by cidrblock** [comment]
the tox.ini file should be updated to reflect the final image as well

**Comment by cidrblock** [comment]
https://github.com/ansible/awx-ee/pull/70

**Comment by cidrblock** [comment]
https://quay.io/repository/ansible/ansible-navigator-demo-ee

we should have a tagged version here by 6/10 per shane
