### ISSUE TITLE
Docs: Missing Table of settings

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#1451]
https://ansible-navigator.readthedocs.io/en/latest/settings/

There should be a table of all settings here, it was previously generated with a python script.

Also right above the settings table, we used to have an example settings file (with options for navigator config/settings file)

**Comment by laurent-indermuehle** [comment]
As a workaround, I run `ansible-navigator settings --sample`. I think it's equivalent. Not sure though.
