### ISSUE TITLE
Doesn't see a playbook when running with docker. With podman works well.

### ISSUE THREAD

**Issue by Andersson007** [ansible/ansible-navigator#1545]
##### ISSUE TYPE

- Bug Report

##### SUMMARY

Doesn't see a playbook when running with docker. With podman works well.
It throws the error `ERROR! the playbook: /root/test_localhost.yml could not be found`

##### ANSIBLE-NAVIGATOR VERSION

```
3.3.1
```

##### CONFIGURATION

Fresh installation, no custom settings

##### LOG FILE

The only entry is:
```
2023-05-09T12:19:58.027513+00:00 CRITICAL 'ansible_navigator.actions.run_playbook._handle_message' Unhandled message from runner queue, discarded: {'event': 'verbose', 'uuid': '99d812d0-3517-4c66-a0d4-060d5e6d2bcd', 'counter': 1, 'stdout': '\x1b[0;31mERROR! the playbook: /root/test_localhost.yml could not be found\x1b[0m', 'start_line': 0, 'end_line': 1, 'runner_ident': '0ddf5377-903e-4681-9c1b-c70a8d060547', 'created': '2023-05-09T12:19:58.026932'}
```

##### STEPS TO REPRODUCE

1. Install docker
2. build the image with ``ansible-builder``
3. create a playbook in your home dir
4. run the following from your home dir
```
[root@fedora03 ~]# ansible-navigator run /root/test_localhost.yml --execution-environment-image postgresql_ee --mode stdout --pull-policy missing
ERROR! the playbook: /root/test_localhost.yml could not be found
Please review the log for errors.
[root@fedora03 ~]# 
[root@fedora03 ~]# 
[root@fedora03 ~]# cat test_localhost.yml 
---
- hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
  - name: Print facts
    ansible.builtin.debug:
      msg: '{{ ansible_facts }}'
```
If I uninstall docker, install podman, rebuild the image with the same build command and definition, and run the same command, everything works as expected
```
[root@fedora03 ~]# ansible-navigator run /root/test_localhost.yml --execution-environment-image postgresql_ee --mode stdout --pull-policy missing
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that
the implicit localhost does not match 'all'

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Print facts] *************************************************************
ok: [localhost] => {
    "msg": {
        "ansible_local": {},
        "apparmor": {
            "status": "disabled"
        },
        "architecture": "x86_64",
...
```

##### EXPECTED RESULTS

No errors. Works well as with podman.

##### ACTUAL RESULTS

```
ERROR! the playbook: /root/test_localhost.yml could not be found
```

**Comment by cidrblock** [comment]
I suspect this is beacuse the user in the container when using docker is 1000, and does not have access to the /root directory where the playbook is being mounted.

We can check this using the `exec` command:

```
(venv) m910x ➜  ansible-navigator git:(main) ✗ ansible-navigator exec --ce docker --eei test-ee --pp never 

dr-xr-x---   1 root root   8 Jun  8 13:30 root
```
Does this work in any directory other than `/root` ?  

If you have to mount the playbook into /root, you might have to be the root user in the container to access it:

```
(venv) m910x ➜  ansible-navigator git:(main) ✗ ansible-navigator exec --ce docker --eei test-ee --pp never --co="--user=root" 
[root@8226ac2388a9 ansible-navigator]# touch /root/foo.txt
[root@8226ac2388a9 ansible-navigator]# 
```

Keep us posted on you findings!

**Comment by Andersson007** [comment]
@cidrblock i'll try the solution next week (probably on Tuesday), thanks a lot

**Comment by Andersson007** [comment]
Yep, it works in another directory.
Our getting-started guide doesn't suggest using `root` and, moreover, we've recently changed it to use a project dir, i.e. not to use a home dir, so should be fine then
I don't think we should add any clarifications about this (i'd say) corner case, 
closing, thanks!
