### ISSUE TITLE
Missing files in .generated in settings.md

### ISSUE THREAD

**Issue by naivary** [ansible/ansible-navigator#1558]
##### ISSUE TYPE

- Doc issue

##### SUMMARY

the settings.md is not generated correctly and is missing some files from .generated.

**Comment by naivary** [comment]
I'm not getting a correctly rendered page when I go to the [settings.md](./docs/settings.md) file. Do you not have the same problem?

**Comment by shatakshiiii** [comment]
So it renders me to https://github.com/ansible/ansible-navigator/blob/main/docs/settings.md , and from there we can see the navigator's settings.md file.

Does that shows you something else ?

**Comment by naivary** [comment]
Yes but in the settings.md there are missing files e.g {!.generated/ansible-navigator.yml!} not the actual content of ansible-navigator.yml

**Comment by naivary** [comment]
Oh. Thank you for pointing it out. Looked like a missing piece for me. Thank you for your time and sorry for the misunderstanding on my behalf.

**Comment by shatakshiiii** [comment]
no problem, Thank you for trying it out!
