### ISSUE TITLE
RFE: please tighten up FAQ entry How can I use a vault password with ansible-navigator

### ISSUE THREAD

**Issue by pcfe** [ansible/ansible-navigator#1571]
##### ISSUE TYPE

- Doc issue

##### SUMMARY

1. when I filed #1559 I overlooked that for the example to work, the last two lines should be shown as one. Sorry, my bad, I could have fixed that alredy when I created #1560.

2. Seeing too often users disregarding security warnings just because they  find an example to copy and paste next to said warning, it would be nice if the FAQ removed the `echo my_password >> ~/.vault_password` example or at least moved it to second place
3. it might be useful to explain the use of bash's HISTCONTROL together with using an env var in a vault password client script a bit more in depth (so that users feel confident to prefer that method over passwords in cleartext on disk).

Since doing is better than just asking :nerd_face:  I'll open an PR shortly with commits to pick or discuss or drop.

**Comment by shatakshiiii** [comment]
Closed by #1572
