### ISSUE TITLE
abilitity to call a playbook included in a collection

### ISSUE THREAD

**Issue by volapuk** [ansible/ansible-navigator#1598]
##### ISSUE TYPE

- Feature Idea

##### SUMMARY

Using ansible-playbook you can call a playbook that is inside an ansible collection this way ansible-playbook namespace.collectionname.playbookname.yml, this behavior should exist in ansible-navigator as well.

**Comment by shatakshiiii** [comment]
We support the same via ansible-navigator run subcommand. 
This way -> `ansible-navigator run namespace.collectionname.playbookname`
