### ISSUE TITLE
Ansible-Navigator role call issue

### ISSUE THREAD

**Issue by ahm3dbajw3** [ansible/ansible-navigator#1612]
##### SUMMARY

when i check the syntax of playbook using ansible-navigator command its showing error but when i check using ansible-playbook command its showing no error 

##### ANSIBLE-NAVIGATOR VERSION

ansible-navigator 3.4.2

##### CONFIGURATION

[devops@control ansible]$ cat ansible.cfg
[defaults]
inventory = inventory
roles_path = /home/devops/ansible/myroles:/usr/share/ansible/roles
collections_path = /home/devops/ansible/mycollections
remote_user = devops
[privilege_escalation]
become = True
become_method = sudo
become_user = root
become_ask_pass = False

##### STEPS TO REPRODUCE

ansible-navigator run timesync.yml --syntax-check -m stdout

##### EXPECTED RESULTS

ERROR! the role '/usr/share/ansible/roles/linux-system-roles.timesync' was not found in /home/devops/ansible/roles:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/devops/ansible

The error appears to be in '/home/devops/ansible/timesync.yml': line 13, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - /usr/share/ansible/roles/linux-system-roles.timesync
      ^ here

##### ACTUAL RESULTS

ERROR! the role '/usr/share/ansible/roles/linux-system-roles.timesync' was not found in /home/devops/ansible/roles:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/devops/ansible

The error appears to be in '/home/devops/ansible/timesync.yml': line 13, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - /usr/share/ansible/roles/linux-system-roles.timesync
      ^ here

##### ADDITIONAL INFORMATION

when we check the playbook syntax using ansible-playbook its working perfect 
below is the output of upper command.

[devops@control ansible]$ ansible-playbook --syntax-check timesync.yml

playbook: timesync.yml

when we check the playbook syntax using ansible-playbook its working perfect 
============
playbook content
============
---
- name: time update
  hosts: all
  vars:
     timesync_ntp_servers:
      - hostname: 0.asia.pool.ntp.org
        iburst: true
      - hostname: 1.asia.pool.ntp.org
        iburst: true
      - hostname: 2.asia.pool.ntp.org
        iburst: true
  roles:
    - /usr/share/ansible/roles/linux-system-roles.timesync

**Comment by ahm3dbajw3** [comment]
Please find below content of playbook
---------------------------------

---
- name: time update
  hosts: all
  vars:
     timesync_ntp_servers:
      - hostname: 0.asia.pool.ntp.org
        iburst: true
      - hostname: 1.asia.pool.ntp.org
        iburst: true
      - hostname: 2.asia.pool.ntp.org
        iburst: true
  roles:
    - /usr/share/ansible/roles/linux-system-roles.timesync

**Comment by cidrblock** [comment]
Can you try this with `--ee false`?  I'm wondering if the role was not mounted into the execution environment and therefore when running in the execution environment it cannot be found.

By default navigator only mounts the current working directory into the container.

If content outside the current working directory is needed within the execution environment, additional volume mount can be added using the CLI and config file: https://ansible.readthedocs.io/projects/navigator/settings/#execution-environment-volume-mounts

Please let us know.

-Brad

**Comment by ahm3dbajw3** [comment]
Dear Mr. Brad,

Thank for your guidence issue is fixed.
