### ISSUE TITLE
Drop setuptools_scm_git_archive dependency

### ISSUE THREAD

**Issue by jose1711** [ansible/ansible-navigator#1712]
##### ISSUE TYPE

- Bug Report

##### SUMMARY

As per "With setuptools-scm >= 7.0.0 the separate use of setuptools-scm-git-archive has become obsolete, as the functionality is now included." at https://archlinux.org/todo/remove-use-of-python-setuptools-scm-git-archive/ it looks like `setuptools_scm_git_archive` is no longer needed with almost a 2-year old `setuptools-scm` (version 7.0.0 was released in June 2022). FWIW the project builds without issues if said module is removed from `pyproject.toml`.

##### ANSIBLE-NAVIGATOR VERSION

current HEAD

**Comment by ssbarnea** [comment]
@jose1711 You are right. Can you please make a PR to address it?
