### ISSUE TITLE
ansible-navigator does not respect "--format" within images sub-command

### ISSUE THREAD

**Issue by alexander-aps** [ansible/ansible-navigator#1857]
##### ISSUE TYPE

- Bug Report

##### SUMMARY

ansible-navigator does not output in JSON when interrogating an Execution Environment.

##### ANSIBLE-NAVIGATOR VERSION

```bash
--> ansible-navigator --version
ansible-navigator 24.9.0

--> /usr/bin/python3 --version
Python 3.12.1
```

##### CONFIGURATION

Default configuration only.

##### LOG FILE

The settings are for DEBUG, but after first removing the log file, and then running the command, the resulting log file is zero bytes

```
ansible-navigator images --execution-environment-image ee-supported-rhel9_azure:latest --details system_packages --format json
```

##### EXPECTED RESULTS

I expect the resulting output to be in JSON format

##### ACTUAL RESULTS

The resulting output is in YAML format

**Comment by shatakshiiii** [comment]
Hey @alexander-aps, I am able to reproduce this issue, we look forward to fix this soon.
Thanks for reporting this here!
