### ISSUE TITLE
Author a json schema file for the ansible-navigator settings file to detect extras

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#188]
The settings file could be checked with a json schema for any extra entries, this would allow ansible-navigator to notify the user if any "extra" entries were found.

This would catch spelling errors, typos, misnamed entries rather than silently ignoring them as happens today.

**Comment by gdykeman** [comment]
+1 this @cidrblock 
ansible-navigator:
   playbook-artifact:
     enabled: False
Had it listed as "enabled" and not "enable" as the docs show.
