### ISSUE TITLE
[DOC]Quick start video guide shows the ansible-navigator prompt screen with incorrect cmd

### ISSUE THREAD

**Issue by justjais** [ansible/ansible-navigator#199]
Quick start video guide shows the `ansible-navigator` prompt screen with incorrect cmd.

Currently the cmd shown is: `ansible-navigator run` resulting to navigator prompt which I believe with recent refactor changes has been changed just to `ansible-navigator`

**Comment by cidrblock** [comment]
TY

**Comment by cidrblock** [comment]
tmms
