### ISSUE TITLE
Refactor `catalog_collections.py` to avoid directly importing from ansible-core

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible-navigator#212]
Currently `catalog_collections.py` directly imports `get_docstring` from `ansible-core`.
To avoid it will require refactor in `worker` method to get the plugin docs using `anisble-runner` API's

**Comment by cidrblock** [comment]
This may not be possible now that #179 is closed

**Comment by cidrblock** [comment]
Closing this. It has been confirmed that ansible-core has no plans to catalog anything but the last instance of a collection found in the list of search directories.
