### ISSUE TITLE
Consider adding roles to what is catalogued within a collection

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#231]

**Comment by dalston** [comment]
This would be a nice feature to have.  I imagine two ways to browse the roles..
1) menu-like list of the roles involved with the ability to open them up in an external editor
2) Search the roles/playbooks for a variable name (or some regex) and get a list of the files you can select from to edit in an external editor

For myself, when I open up a role for editing I like to see the variables and the tasks at the same time.  I usually use something like this..

vim -O defaults/main.yml tasks/main.yml

I've written a BASH script that performs the functions I've suggested here.  You're welcome to take a look and use whatever you want from it.
[virole.txt](https://github.com/ansible/ansible-navigator/files/6908193/virole.txt)

**Comment by samccann** [comment]
FWIW - with the new roles arspec in place, we have the start of documentation autogeneration from roles. You can see it in this PR - https://github.com/ansible-community/antsibull/pull/272 and the places it links to. I expect that will be merged shortly, and it's something that navigator could display per role (for roles that use the argspec).
