### ISSUE TITLE
Readme - some grammatical corrections

### ISSUE THREAD

**Issue by alisondudiak** [ansible/ansible-navigator#235]
In the Readme...some of the full sentences have periods and some dont... (Quickstart vs. Welcome).  Also "By default, ansible-navigator uses execution environments, to use ansible-navigator without an execution enviroment, ansible is required"...would it sound better as.... "By default, ansible-navigator uses execution environments,.  To use ansible-navigator without an execution enviroment, ansible is required."

**Comment by cidrblock** [comment]
TY!

**Comment by Akasurde** [comment]
resolved_by_pr #240
