### ISSUE TITLE
Readme -  some grammatical corrections

### ISSUE THREAD

**Issue by alisondudiak** [ansible/ansible-navigator#236]
Quickstart
By default, ansible-navigator uses execution environments, to use ansible-navigator without an execution enviroment, ansible is required
change to - By default, ansible-navigator uses (an?) execution environment. To use ansible-navigator without an execution enviroment, ansible is required.   (also - .... to use ansible-navigator without an execution **enviroment**  (enviroment is spelled incorrectly.)

Welcome
Start at the welcome page, from the welcome page you can run playbooks, browse collections, explore inventories, review docs and more.
Change to 2 sentences - 
Start at the Welcome page. From the Welcome page you can run playbooks, browse collections, explore inventories, review docs and more.    (Not sure if you want to capitalize Welcome since its a title)

Other things to try direct from the command line  - should it be "directly?"

- Using interactive mode, which is the default  - change to "Using  (the default) interactive mode, or "Using interactive mode (the default mode)

-  Review and explore documentation (default mode is interactive)  - remove " (default mode is interactive) since it is already stated in this section

Key bindings and colon commands
While using the terminal user interface keys and commands are avilable, the following is also available within the application by typing :help:

Change to 2 sentences. -  While using the terminal user interface, keys and commands are avilable (available is spelled incorrectly).  The following is also available within the application by typing :help:

**Comment by Akasurde** [comment]
resolved_by_pr #240
