### ISSUE TITLE
ansible-navigator: how to pass environment variables?

### ISSUE THREAD

**Issue by goneri** [ansible/ansible-navigator#250]
Hi!

I've an `ANSIBLE_ROLES_PATH` environment variable and it looks like `ansible-navigator` ignores it. Is this by design? if so, what is the right way to use an extra role directory?

**Comment by goneri** [comment]
If I pass `--ee false`, `ansible-navigator` uses the environment variable. It's a bit confusing, I would expect the same behaviour in both cases.

**Comment by goneri** [comment]
I also try to pass some more variables to configure the vmware modules and they are ignored.

**Comment by cidrblock** [comment]
@goneri run with --log-level debug, I suspect the envar is being passed off but the path isn't volume mounted, custom volume mounting is coming at some point
