### ISSUE TITLE
'% COMPLETED' doesn't seem to show the real completion percentage

### ISSUE THREAD

**Issue by alinabuzachis** [ansible/ansible-navigator#263]
`% COMPLETED` doesn't seem to show the real completion percentage.
I run a playbook with several tasks in and one in particular requires a couple of minutes to spawn an RDS instance. As you can see in the attached figure, there is one task in progress (the one that requires a couple of minutes), but the completion in 100%. 

![image](https://user-images.githubusercontent.com/49211501/118190520-83160900-b443-11eb-951f-01bb7f896d85.png)

By doing `:stdout`, it's evident that the task hasn't completed yet.

![image](https://user-images.githubusercontent.com/49211501/118190743-d720ed80-b443-11eb-9940-ecdab5c0c6db.png)

With another playbook, `% COMPLETED` seems showing a progressive completion percentage (50%, 80%,...), as I would expect.

**Comment by cidrblock** [comment]
this one is tricky, it shouldn't say 100% unless it's done.  The only way to determine % complete was to use the number of completed tasks as a % of the total (which would include pending tasks).  When the number of hosts is small and things come to a pause, there is not pending tasks so the completed is a +99% of the total and it's rounded. 

there's no way to _really_ know what the % completed is, just due to the nature of how ansible works and the task list can change size based on the outcome of later tasks.

will see what can be done to make sure it's not at 100% when it should be, but I don't think it will every really be "accurtate"

**Comment by bonnevil** [comment]
> this one is tricky, it shouldn't say 100% unless it's done. The only way to determine % complete was to use the number of completed tasks as a % of the total (which would include pending tasks). When the number of hosts is small and things come to a pause, there is not pending tasks so the completed is a +99% of the total and it's rounded.

Wouldn't using a floor function rather than rounding up "solve" the problem?  It's the overestimate, not the underestimate, that's confusing.

**Comment by alinabuzachis** [comment]
> this one is tricky, it shouldn't say 100% unless it's done. The only way to determine % complete was to use the number of completed tasks as a % of the total (which would include pending tasks). When the number of hosts is small and things come to a pause, there is not pending tasks so the completed is a +99% of the total and it's rounded.
> 
> there's no way to _really_ know what the % completed is, just due to the nature of how ansible works and the task list can change size based on the outcome of later tasks.
> 
> will see what can be done to make sure it's not at 100% when it should be, but I don't think it will every really be "accurate"

Thank you for your clear explanation. I think there is also a problem with the task count because that playbook had 7 tasks in. In fact, after the task requiring a couple of minutes has finished, the number of tasks has been updated. As you can see, the completion percentage is still 100 % even if it didn't complete all the tasks.

![image](https://user-images.githubusercontent.com/49211501/118309023-f7f14d80-b4ec-11eb-8694-94a046a3e257.png)

![image](https://user-images.githubusercontent.com/49211501/118309124-1bb49380-b4ed-11eb-9d75-39aa3c46381f.png)

**Comment by cidrblock** [comment]
floor might just do the trick, this is where that happens https://github.com/ansible/ansible-navigator/blob/main/ansible_navigator/actions/run.py#L635. You'll see a little logic in there to make sure it doesn't go backwards, which can happen when a flood of pending tasks comes in based on playbook logic

I'll label this accordingly, ty

**Comment by cidrblock** [comment]
the more I think about this, I wonder of the xx% should be dropped all together, leaving just the status bar and possible change it's state when the play is complete. (similar to how zuul does it)
