### ISSUE TITLE
Enabling artifact creation with mode stdout causes playbooks requiring user input to hang 

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#341]
re #277 
re #340 
re #91

**Comment by cidrblock** [comment]
we might be able to do something if we see a playbook_on_vars_prompt....

**Comment by webknjaz** [comment]
@cidrblock does this need to be open?

**Comment by cidrblock** [comment]
This is documented in the FAQ, I'm not sure there is much else to be done at this time.
