### ISSUE TITLE
[tests] Sanitize DEFAULT_LOCAL_TMP in fixtures

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#346]
See #345 for some examples

**Comment by ganeshrn** [comment]
Clean the runner UUID created at line https://github.com/cidrblock/ansible-navigator/blob/3e1b29fd0cdab2ea28fc22553a5c514cfcbc7fea/tests/fixtures/integration/actions/config/test_welcome_interactive_specified_config.py/test/1.json#L94 from output
