### ISSUE TITLE
OOTB install on Mac OSX doesn't work

### ISSUE THREAD

**Issue by ffirg** [ansible/ansible-navigator#362]
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241

Installed as per README quickstart:
mkdir project_directory
cd project_directory
python3 -m venv venv
source venv/bin/activate
pip install ansible-navigator

ansible-navigator config
[ERROR]: Command provided: 'config'
[ERROR]: The specified container engine could not be found:'podman', set by 'default configuration value'
[ERROR]: Configuration failed, using default log file location: /Users/pgriffit/ansible-navigator-testing/ansible-navigator.log. Log level set to debug

There is no podman on Mac. Perhaps we should check for docker as well, or set as the default for non-RHEL installs?

ansible-navigator --ce docker config works but this is a hurdle for getting people started quickly OOTB.

**Comment by cidrblock** [comment]
TY again, great idea!
