### ISSUE TITLE
ansible-navigator.yml config file not being picked up unless set as ENV var

### ISSUE THREAD

**Issue by ffirg** [ansible/ansible-navigator#363]
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241

Created venv as per quickstart.
Inside the project dir created an ansible-navigator.yml - navigator not picking this up
Moved ansible-navigator.yml to ~ (home dir) - navigator not picking this up

export ANSIBLE_NAVIGATOR_CONFIG="/Users/pgriffit/ansible-navigator.yml"
navigator now picking up the config file

For reference this is my config settings:
grep -v "#" /Users/pgriffit/ansible-navigator.yml
---
ansible-navigator:
  execution-environment:
    container-engine: docker
    enabled: True
  logging:
    level: critical

**Comment by cidrblock** [comment]
Ty for trying it out!

In the home directory it should be .ansible-navigator.yml   (with a dot)

I'll check on the project directory case, these just got cleaned up

**Comment by ffirg** [comment]
Ah thanks, missed the dot in the homedir.
Shouldn't it also be a dot for the projectdir as well then?
The docs might need a tweak? https://github.com/ansible/ansible-navigator/blob/main/docs/settings.rst#the-ansible-navigator-settings-file

**Comment by ffirg** [comment]
Still not working for me.


(venv) pgriffit@pgriffit1-mac:~/ansible-navigator-testing: ls -l ~/.ansible-navigator.yml
-rw-r--r--  1 pgriffit  staff  1112 27 May 16:33 /Users/pgriffit/.ansible-navigator.yml

(venv) pgriffit@pgriffit1-mac:~/ansible-navigator-testing: ansible-navigator config dump -m stdout

[ERROR]: Command provided: 'config dump -m stdout'
[ERROR]: The specified container engine could not be found:'podman', set by 'default configuration value'
[ERROR]: Configuration failed, using default log file location: /Users/pgriffit/ansible-navigator-testing/ansible-navigator.log. Log level set to debug

But...
export ANSIBLE_NAVIGATOR_CONFIG="/Users/pgriffit/ansible-navigator.yml"
makes it work.

**Comment by cidrblock** [comment]
ERGH.

The docs and the pypi package are out of sync.

We'll have a release on 6/1, can you wait until then or try from source?

Sorry about that... LMK

TY again for checking it out

**Comment by ffirg** [comment]
HI Bradley. Happy to wait for the next release and I'll try it out again. Thanks. Phil.

**Comment by ffirg** [comment]
tried out ansible-navigator 1.0.0a1 seems to be picking up my project config file now, so closing this one off.
