### ISSUE TITLE
playbook hangs "running" from navigator but works using ansible-playbook

### ISSUE THREAD

**Issue by ffirg** [ansible/ansible-navigator#418]
Running some simple tests in a venv. 

sw_vers
ProductName:	macOS
ProductVersion:	11.3.1
BuildVersion:	20E241

ansible --version
ansible [core 2.11.1]
  config file = None
  configured module search path = ['/Users/pgriffit/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pgriffit/ansible-navigator-testing/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/pgriffit/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/pgriffit/ansible-navigator-testing/venv/bin/ansible
  python version = 3.9.4 (default, Apr  5 2021, 01:50:46) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True

cat ~/a.yml
```bash
---
- name: Demo for Ansible Navigator Tool
  hosts: localhost

  vars:
    timeout: 5

  tasks:

    - name: "Oh hello!"
      ansible.builtin.ping:

    - name: "And chillax for {{ timeout }} seconds..."
      ansible.builtin.pause:
        seconds: 5

    - name: "Stop memcached"
      community.general.launchd:
        name: org.memcached
        state: stopped
```

Running this using ansible-playbook works (the memcached failure is expected):
ansible-playbook ~/a.yml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: Found variable using reserved name: timeout

PLAY [Demo for Ansible Navigator Tool] *****************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [localhost]

TASK [Oh hello!] ***************************************************************************************************************************
ok: [localhost]

TASK [And chillax for 5 seconds...] ********************************************************************************************************
Pausing for 5 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [Stop memcached] **********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to infer the path of org.memcached service plist file"}

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

But when run using ansible-navigator run ~/a.yml it hangs in the GUI showing RUNNING.
I have to quit out using :q!

I saved the run state before quitting:
cat saved
{
    "version": "1.0.0",
    "plays": [],
    "stdout": [],
    "status": "running",
    "status_color": 10

debug logging has:
210602133932.156 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: envvars:{}
210602133932.156 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: cwd:/Users/pgriffit/ansible-navigator-testing
210602133932.156 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: executable_cmd:ansible-playbook
210602133932.156 DEBUG 'ansible_navigator.runner.api.generate_run_command_args' Runner arg: cmdline_args:['/Users/pgriffit/a.yml']
210602133932.158 DEBUG 'ansible_navigator.actions.run_3680._run_runner' runner requested to start
210602133932.158 INFO 'ansible_navigator.actions.run_3680._init_run' Run initialized and playbook started.
210602133932.265 DEBUG 'ansible_navigator.actions.run_3680._take_step' autoscroll enabled
210602134021.801 DEBUG 'ansible_navigator.actions.save.run' save requested

but nothing to indicate why it hangs.

**Comment by ffirg** [comment]
It works by using ansible-navigator --execution-environment false run ~/a.yml

**Comment by cidrblock** [comment]
Can you tell me which `ansible-navigator --version` this is with please?  

^^^ good info, ty

**Comment by cidrblock** [comment]
(based on the empty playbook artifact, I suspect this might be an older version but hoping you can confirm)

**Comment by ffirg** [comment]
no latest and greatest unfortunately.
ansible-navigator --version
ansible-navigator 1.0.0a1

**Comment by cidrblock** [comment]
```
mkdir 418
cd 418
python -m venv venv
source venv/bin/activate
vi site.yaml
pip install ansible-navigator==1.0.0a1
pip install ansible-core
ansible-galaxy collection install community.general -p ./collections
ansible-navigator
ansible-navigator --version
ansible-navigator run site.yaml
```

we could use the full log here too, I just tried to recreate this one as well....

**Comment by ffirg** [comment]
Your example also worked for me :)
Going to run through a few more scenarios to see if I can reproduce the error in any way.
I installed ansible rather than ansible-core before so will see about that.

**Comment by ffirg** [comment]
Ok seems to be the way the collection is parsed/used when you install ansible rather than ansible-core, as this produces an error in -navigator but runs fine in -playbook

mkdir test2
cd test2
python -m venv venv
source venv/bin/activate
vi site.yaml
pip install ansible-navigator==1.0.0a1
pip install ansible

ansible-navigator --version = ansible-navigator 1.0.0a1

ansible --version
ansible [core 2.11.1]
  config file = None
  configured module search path = ['/Users/pgriffit/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pgriffit/test2/venv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/pgriffit/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/pgriffit/test2/venv/bin/ansible
  python version = 3.9.4 (default, Apr  5 2021, 01:50:46) [Clang 12.0.0 (clang-1200.0.32.29)]
  jinja version = 3.0.1
  libyaml = True

ansible-galaxy collection list | grep community.general
community.general               1.3.0 (# /Users/pgriffit/.ansible/collections/ansible_collections)
community.general             3.0.2. (# /Users/pgriffit/test2/venv/lib/python3.9/site-packages/ansible_collections)

```bash
ansible-playbook site.yaml
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: Found variable using reserved name: timeout

PLAY [Demo for Ansible Navigator Tool] *****************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [localhost]

TASK [Oh hello!] ***************************************************************************************************************************
ok: [localhost]

TASK [And chillax for 5 seconds...] ********************************************************************************************************
Pausing for 5 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [Stop memcached] **********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to infer the path of org.memcached service plist file"}

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

![Screenshot 2021-06-03 at 11 23 16](https://user-images.githubusercontent.com/8989994/120629807-19938400-c45e-11eb-8b2b-57508e327624.png)

stdout produces this in -navigator too:
```bash
 0│[WARNING]: You are running the development version of Ansible. You should only
 1│run Ansible from "devel" if you are modifying the Ansible engine, or trying out
 2│features under development. This is a rapidly changing source of code and can
 3│become unstable at any point.
 4│[WARNING]: You are running the development version of Ansible. You should only
 5│run Ansible from "devel" if you are modifying the Ansible engine, or trying out
 6│features under development. This is a rapidly changing source of code and can
 7│become unstable at any point.
 8│[WARNING]: No inventory was parsed, only implicit localhost is available
 9│[WARNING]: provided hosts list is empty, only localhost is available. Note that
10│the implicit localhost does not match 'all'
11│ERROR! couldn't resolve module/action 'community.general.launchd'. This often indicates a misspelling, missing collection, or incorrect m
12│
13│The error appears to be in '/Users/pgriffit/test2/site.yaml': line 17, column 7, but may
14│be elsewhere in the file depending on the exact syntax problem.
15│
16│The offending line appears to be:
17│
18│
19│    - name: "Stop memcached"
20│      ^ here
```

**Comment by ffirg** [comment]
I removed community.general from /Users/pgriffit/.ansible/collections/ansible_collections/community/general so that it picked up from /Users/pgriffit/test2/venv/lib/python3.9/site-packages/ansible_collections/community/general but same issue

**Comment by cidrblock** [comment]
ok....  I think this has to do with how and what gets mounted into the EE.  Only the CWD/playbook/inventory is mounted by default, yesterday I added an entry in the FAQ that might explain this...  https://github.com/ansible/ansible-navigator/blob/main/docs/faq.md

Let me know if that helps or can be explained better in the FAQ...

**Comment by ffirg** [comment]
Ok, thanks. That makes sense and explains my error, but I would expect
-navigator to work the same as -playbook and pick up the default
environment collection paths?
As my example is using builtin collections as well, I wouldn't expect to
have to install them again under a local path?

**Comment by cidrblock** [comment]
It's a tricky space.... We want to make sure the user consciously has to configure navigator for scenarios that won't immediately work with controller/tower and awx. ansible-navigator isn't intended to be a plug and play replacement for ansible-playbook, but instead a bridge to a production deployment of a playbook.
