### ISSUE TITLE
 ansible-navigator inventory hangs

### ISSUE THREAD

**Issue by ffirg** [ansible/ansible-navigator#420]
cat /Users/pgriffit/workshops.devel/vagrant-demo/labs/hosts
[leafs]
leaf01 ansible_host=172.16.10.11 ansible_network_os=vyos
leaf02 ansible_host=172.16.10.12 ansible_network_os=vyos

[spines]
spine01 ansible_host=172.16.10.13 ansible_network_os=vyos
spine02 ansible_host=172.16.10.14 ansible_network_os=vyos

[network:children]
leafs
spines

[servers]
server01 ansible_host=172.16.10.15
server02 ansible_host=172.16.10.16

[datacenter:children]
leafs
spines
servers

ansible-navigator inventory -i /Users/pgriffit/workshops.devel/vagrant-demo/labs/hosts
just hangs (blank screen).

Logs show very little:
210602142559.134 DEBUG 'ansible_navigator.actions.inventory._update_args' Running with osc4 as 'True' (bool/default configuration value)
210602142559.134 DEBUG 'ansible_navigator.actions.inventory._update_args' Running with pass_environment_variable as 'Constants.NOT_SET' (Constants/value has not been set)
210602142559.134 DEBUG 'ansible_navigator.actions.inventory._update_args' Running with playbook as 'Constants.NOT_SET' (Constants/value has not been set)
210602142559.134 DEBUG 'ansible_navigator.actions.inventory._update_args' Running with playbook_artifact_enable as 'True' (bool/default configuration value)
210602142559.134 DEBUG 'ansible_navigator.actions.inventory._update_args' Running with playbook_artifact_replay as 'Constants.NOT_SET' (Constants/value has not been set)
210602142559.134 DEBUG 'ansible_navigator.actions.inventory._update_args' Running with playbook_artifact_save_as as '{playbook_dir}/{playbook_name}-artifact-{ts_utc}.json' (str/default configuration value)
210602142559.134 DEBUG 'ansible_navigator.actions.inventory._update_args' Running with plugin_name as 'Constants.NOT_SET' (Constants/value has not been set)
210602142559.134 DEBUG 'ansible_navigator.actions.inventory._update_args' Running with plugin_type as 'module' (str/default configuration value)
210602142559.134 DEBUG 'ansible_navigator.actions.inventory._update_args' Running with pull_policy as 'tag' (str/default configuration value)
210602142559.135 DEBUG 'ansible_navigator.actions.inventory._update_args' Running with set_environment_variable as 'Constants.NOT_SET' (Constants/value has not been set)

**Comment by cidrblock** [comment]
thx again, can you confirm the ansible-navigator --version here too please?

what's not to like about an issue w/ a network inventory :)

**Comment by ffirg** [comment]
Ah sorry forgot! 
ansible-navigator --version
ansible-navigator 1.0.0a1

**Comment by cidrblock** [comment]
Can you paste in a complete log, `--ll debug --la false` and try it again?  I copied your inventory over and couldn't recreate the issue...

(appreciated)

**Comment by ffirg** [comment]
With a fresh venv install it's now working.

**Comment by ffirg** [comment]
Can't reproduce with new venv, so considering resolved.
