### ISSUE TITLE
[issue bug report] -  we could change the order of items, in the way that the context comes before the configuration items.

### ISSUE THREAD

**Issue by yagomarques** [ansible/ansible-navigator#451]
### Summary

my suggestion is those 3 items should be higher up on the form, I think it makes viewing easier.
- Steps to Reproduce
- Expected Results
- Actual Results

who are going to fix it, it's better to have the context before the configuration, at least that's how I imagine it.

### Issue Type

Feature Idea

### Additional Information

check this issue, https://github.com/ansible/ansible-navigator/issues/450, the important informations about the scenario are at the end.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by cidrblock** [comment]
+1
