### ISSUE TITLE
Comma separated lists don't work 

### ISSUE THREAD

**Issue by shanemcd** [ansible/ansible-navigator#457]
### Summary

This works:

```
$ ansible-navigator -m stdout run ~/ansible-runner/demo/project/test.yml -i localhost, -c local
```

This does not:
![image (2)](https://user-images.githubusercontent.com/773186/121055549-5aa3d500-c78b-11eb-8f43-7d1359357a61.png)

### Issue Type

Bug Report

### Ansible-navigator Version

```console
54b92f9a80ced72a135dd2f708806b3eca119cdc
```

### Ansible-runner Version

```console
2.0.0.0a5
```
```


### Settings

```console
N/A
```

### Command

```console
See above
```

### Ansible Version

```console
N/A
```

### Ansible Configuration

```console
$ ansible-navigator config dump --only-changed -m stdout
```

### OS / Environment

Fedora 34

### Steps to Reproduce

See issue summary

### Expected Results

See issue summary

### Actual Results

```console
See issue summary
```

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by s-hertel** [comment]
FYI (since I don't have access to assign myself), I'm working on a fix for this.
