### ISSUE TITLE
Include ansible-builder functionality

### ISSUE THREAD

**Issue by ffirg** [ansible/ansible-navigator#459]
### Summary

Have ansible-builder functionality within navigator.

### Issue Type

Feature Idea

### Additional Information

I would like to be able to produce and test an EE using ansible-navigator builder as an option.

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by s-hertel** [comment]
+1, seems like this would be handy.

**Comment by mnecas** [comment]
+1

**Comment by ffirg** [comment]
sweet! nice work!
