### ISSUE TITLE
[:RUN] all playbooks executions are failing on version 0.7.1

### ISSUE THREAD

**Issue by yagomarques** [ansible/ansible-navigator#462]
### Summary

Today, i just updated my local repo with the new changes and use the `pip install -U ../ansible-navigator/` 

i'm on debug mode, but there is nothing related on the `ansible-navigator.log`

When i tried to run a playbook, i received an visual error(FAILED), i did a downgrade to run the same scenario with the 0.7.0 version, and it's working.

### Issue Type

Bug Report

### Ansible-navigator Version

```console
ansible-navigator 0.7.1
```

### Ansible-runner Version

```console
2.0.0.0a5
```

### Settings

```console
ansible-navigator:
#   app: run
#   collection-doc-cache-path: /tmp/cache.db
#   cmdline: "--forks 15"
#   editor:
#     command: vim_from_setting
#     console: False
#   documentation:
#     plugin:
#       name: shell
#       type: become
  execution-environment:
    image: "quay.io/ansible/awx-ee:devel"
    enabled: True

  log:
    level: debug
```

### Command

```console
$ ansible-navigator
```

### Ansible Version

```console
$ ansible --version
```

### Ansible navigator logs

```console
210608144616.805 WARNING 'ansible_navigator.actions.run_1cf0._update_args' Configuration errors encountered, rolling back to previous configuration.
210608144616.806 WARNING 'ansible_navigator.actions.run_1cf0._update_args' Command provided: 'run'
210608144616.806 WARNING 'ansible_navigator.actions.run_1cf0._update_args' A playbook is required when using the run subcommand

```
```


### Execution environment details

```console
awx-ee:devel
```

### Container enginer details

```console
$ podman info
```

### Ansible Configuration

```console
$ ansible-navigator config dump --only-changed -m stdout
```

### OS / Environment

Fedora

### Steps to Reproduce

1. run `:ansible-navigator your-playbook.yml -i inv`
2. on the RUN page, you gonna see the error
![image](https://user-images.githubusercontent.com/18562328/121207255-87212500-c84f-11eb-8eeb-2f04b6d46ed1.png)
3. if you check the `ansible-navigator.log`, there is nothing related to.
4. you could do a downgrade using the pip, going to the 0.7.0, when you run the same command it will works.

### Expected Results

Should to see the playbook running and passing.

### Actual Results
![image](https://user-images.githubusercontent.com/18562328/121207255-87212500-c84f-11eb-8eeb-2f04b6d46ed1.png)

### Code of Conduct

- [X] I agree to follow the Ansible Code of Conduct

**Comment by s-hertel** [comment]
FYI (since I don't have access to assign myself), I'm working on a fix for this.

**Comment by s-hertel** [comment]
I thought I had a reproducer, but I don't actually. It may be good for someone who knows the code base better to take a look.

@yagomarques If you want to post some of the additional clues you found regarding this, adding them here may be helpful for others taking a look.

**Comment by ganeshrn** [comment]
Even I am not able to reproduce the issue.
```
 ansible-navigator --version
ansible-navigator 0.7.1
```

![Screen Shot 2021-06-10 at 11 18 53 AM](https://user-images.githubusercontent.com/5292461/121471813-ead95880-c9dd-11eb-88ba-50f94624ffa1.png)
![Screen Shot 2021-06-10 at 11 19 22 AM](https://user-images.githubusercontent.com/5292461/121471839-f298fd00-c9dd-11eb-84c6-a3c802322c38.png)

**Comment by ganeshrn** [comment]
@@yagomarques  Can you please share the playbook and ansible-navigator log file with debug mode enabled. You share the entire log file using https://gist.github.com/

**Comment by yagomarques** [comment]
Hey @ganeshrn @s-hertel,

So, i might could be better we close this issue. I am not able to reproduce it anymore, i think was a configuration problem, after the reinstall it's working.

-------- 
About it that @s-hertel 's comment:
> I thought I had a reproducer, but I don't actually. It may be good for someone who knows the code base better to take a look.
> 
> @yagomarques If you want to post some of the additional clues you found regarding this, adding them here may be helpful for others taking a look.

I might gonna create a new issue, because it's related to `network-ee` like images. It looks like there are two different problems with similar impacts. 

Putting them together in the same issue, could to make things more confusing.

So, for now, i gonna close this issue. We could reopen it in the future if you all don't agree.

Thanks for the help and effort!
