### ISSUE TITLE
Improve tests for inventory

### ISSUE THREAD

**Issue by s-hertel** [ansible/ansible-navigator#481]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Inventory needs improved tests: https://github.com/ansible/ansible-navigator/pull/460#pullrequestreview-680374384

* Test inventory sources can be arbitrary strings
* Test successfully parsed inventory can be empty
* Test successfully parsed inventory can have no host vars
* Test inventory failures are displayed

**Comment by cidrblock** [comment]
The inventory tests are in place with the addition of ansible.cfg support in 2.0
