### ISSUE TITLE
On RHEL - If User A, use ansible-navigator and User B try to run ansible-navigator. User B will receive an error

### ISSUE THREAD

**Issue by yagomarques** [ansible/ansible-navigator#493]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
When two users are trying to use Ansible Navigator in the same place, the second user to use, will receive an error:
`PermissionError: [Errno 13] Permission denied: '/tmp/ansible-navigator/artifacts'`

It occurs because the `/tmp/ansible-navigator` is owned by User A and User B may not have permission to write in it.

##### ANSIBLE-NAVIGATOR VERSION
`ansible-navigator 1.0.0rc2`

##### STEPS TO REPRODUCE
1. login as User A, use Navigator
2. login as User B, run `ansible-navigator collections`
3. the error will occurs
`PermissionError: [Errno 13] Permission denied: '/tmp/ansible-navigator/artifacts'`

##### EXPECTED RESULTS
User B should be able to see all informations on Ansible Navigator

##### ACTUAL RESULTS
User B received the error above

**Comment by wenottingham** [comment]
If this is a fixed `/tmp/ansible-navigator`, that also can lead to vulnerabilities. Should use `mkdtemp` or similar to create any temporary directories.

**Comment by cidrblock** [comment]
this is the dir for runner artifacts, https://github.com/ansible/ansible-navigator/blob/main/ansible_navigator/runner/api.py#L90, just a default parent directory. A new one could be created everytime, that's comes with some trouble in the troubleshooting dept...
