### ISSUE TITLE
Switch from Named to mkstemp

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#499]
https://github.com/ansible/ansible-navigator/blob/b7d6fd223f9f55fb5d176b60a687782135a9ae4b/ansible_navigator/actions/open_file.py#L91

- credit @abadger 

So one issue is portability, there's a race where the filehandle opened by `tempfile.NamedTemporaryFile()` hasn't been closed yet when `open(filename, "w")` is called.  On systems where the file can't be opened twice at the same time, that will fail.

The other one is security.  Because of the same race, sometimes the filename will be deleted before `open(filename, "w")` is called.  That gives an attacker a brief window to put their own file, symlink, etc, in place.  IIRC, a symlink would allow the attacker to overwrite one of the user's file with the data, corrupting that file.

**Comment by webknjaz** [comment]
This issue may address the pylint violations listed @ https://github.com/ansible/ansible-navigator/issues/539.

**Comment by cidrblock** [comment]
This function operates exactly as TemporaryFile() does, except that the file is guaranteed to have a visible name in the file system (on Unix, the directory entry is not unlinked). That name can be retrieved from the name attribute of the returned file-like object. Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later). If delete is true (the default), the file is deleted as soon as it is closed. The returned object is always a file-like object whose file attribute is the underlying true file object. This file-like object can be used in a with statement, just like a normal file.

https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile
