### ISSUE TITLE
Add an option to disable `tls-verify` for the EE pull.

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#505]
This should default to True, as verification would be the desired behavior.

maybe something like:

```
ansible-navigator:
  execution-environment:
    tls-verification:
```

**Comment by cidrblock** [comment]
will most likely be implemented as "additional container engine options"

**Comment by ganeshrn** [comment]
> will most likely be implemented as "additional container engine options"

The support for additional container engine options was added as part of PR https://github.com/ansible/ansible-navigator/pull/511
