### ISSUE TITLE
No stdout when running playbook

### ISSUE THREAD

**Issue by mnecas** [ansible/ansible-navigator#519]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When I run some playbook with navigator with stdout mode it shows only the config and no tasks even if it passes.
`ansible-navigator run playbook.yml --eei ovirt:local4 -vvv -m stdout`
Please check out the ansible-navigator.log
##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 1.0.0
```

##### LOG FILE

[ansible-navigator.log](https://github.com/ansible/ansible-navigator/files/6892096/ansible-navigator.log)

**Comment by cidrblock** [comment]
Maybe related to: https://github.com/ansible/ansible-runner/pull/759

**Comment by mnecas** [comment]
confirmed fixed by the related runner PR

**Comment by cidrblock** [comment]
ty @mnecas
