### ISSUE TITLE
AR rotate artifats count does not work

### ISSUE THREAD

**Issue by mnecas** [ansible/ansible-navigator#520]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When running 
`ansible-navigator run playbook.yml --eei ovirt:local -vvv -m stdout --rad /tmp/test`
it creates the artifacts dir with all files and it stays there.
But when I run
`ansible-navigator run playbook.yml --eei ovirt:local -vvv -m stdout --rad /tmp/test --rac 0`
it creates the dir only when running and after the playbook finishes it removes the artifacts dir.
The same goes when I put there any number.

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 1.0.0
```

##### CONFIGURATION

Ansible runner version (master release)
```
❯ ansible-runner --version
2.0.0.0a4.dev69
```

**Comment by cidrblock** [comment]
Related: https://github.com/ansible/ansible-navigator/issues/497
