### ISSUE TITLE
Is there a reason "ansible-navigator inventory" does not use the ansible.cfg inventory setting by default?

### ISSUE THREAD

**Issue by bonnevil** [ansible/ansible-navigator#523]
##### ISSUE TYPE
 - Feature request

##### SUMMARY
Currently, `ansible-navigator inventory` expects to be passed a `-i` option in order to function in CLI mode, and in interactive mode it expects to be given a list of inventory sources to evaluate.

I think that most of the former Ansible tools assumed that if an inventory file wasn't specified, to use the `inventory` setting from the current Ansible configuration (`ansible.cfg` and friends).  It feels like this would make more sense as a default source to use for its analysis if the `-i` option is not specified, in part because it would be useful for troubleshooting what Ansible thinks the current inventory looks like from the working directory in which `ansible-navigator` was run.

**Comment by cidrblock** [comment]
Related: https://github.com/ansible/ansible-navigator/issues/577

**Comment by cidrblock** [comment]
Fixed in version 2, the ansible.cfg entry will be used if nothing is provided to navigator.
