### ISSUE TITLE
ansible navigator requires later version of py yaml but isn't specified

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#525]
From Nicholas:

Thanks, I will play around with it a bit more. And just because I have you here, I navigator was crashing in my setup with TypeError: dump_all() got an unexpected keyword argument 'sort_keys'. I fixed it with pip install --upgrade PyYAML (I was on version 3.12, went to 5.x)

The version can be checked or it can go in a try/except for the sort keys

**Comment by nleiva** [comment]
It looks like `sort_keys` was added in this [commit](https://github.com/yaml/pyyaml/commit/07c88c6c1bee51439a00bc07827980fbb161a1ad), around the date they released PyYAML 5.1, which would then make this release the minimum version required to run Ansible Navigator.
