### ISSUE TITLE
Allow for interactive development within the container

### ISSUE THREAD

**Issue by ericzolf** [ansible/ansible-navigator#526]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Developing automation is very incremental so it's a lot of editing, trying, editing, trying, especially at the beginning. The current ansible-navigator approach stays a bit in the way of this approach, with the overhead of the TUI and each time starting a new container. A mode by which the developer could just be put inside the container as themself and could there edit their code and/or start `ansible-playbook` themselves would help a lot.

Basically, it would be the equivalent of `podman run [--rm] --tty --interactive -v /home/myuser/github/pull-test/:/home/myuser/github/pull-test/ --workdir /home/myuser/github/pull-test -v /run/user/1000/keyring/:/run/user/1000/keyring/ -e SSH_AUTH_SOCK=/run/user/1000/keyring/ssh -v /home/myuser/.ssh/:/home/runner/.ssh/ --group-add=root --userns=keep-id  --user="$(id -u):$(id -g)" --ipc=host -v /tmp/ansible-navigator_th4mlx94/artifacts/:/runner/artifacts/:Z -v /tmp/ansible-navigator_th4mlx94/:/runner/:Z --env-file /tmp/ansible-navigator_th4mlx94/artifacts/d8722364-68c8-4875-973e-8d1234008533/env.list --quiet --name ansible_runner_d8722364-68c8-4875-973e-8d1234008533 registry.blup/bla/ansible-automation-platform-20-ee-supported-rhel8:latest /bin/bash`.

Two comments:
1. notice the addition of `--userns=keep-id  --user="$(id -u):$(id -g)"` to make sure that the user is themself within the container and the access right remain correct.
2. being able to keep the container across calls i.e. without `--rm` would also help, for example with the ability to give a fix name to the container, as the developer could then customize it with aspects irrelevant to the automation itself (i.e. add their favourite editor) without having to create an own image.

Thinking about it, that also means that the temporary directory `/tmp/ansible-navigator_th4mlx94` would be persistent, the location `/tmp` isn't a perfect place for this kind of approach, so it should also be moved, e.g. to a sub-directory of the current directory.

**Comment by anshulbehl** [comment]
Few good to have things in future with navigator would also be to have
- An easy way to run setup module or ad-hoc modules like ping
- Like `ansible all -m setup` or `ansible all -m ping`

This way its easier to take that first step to understand ansible modules without dealing with navigator in a deep dive fashion like setting up config or knowing about interactive or stdout modes.

A first easy step and then you would need to understand the module and navigator function to achieve something meaninful.
