### ISSUE TITLE
Have a subcommand that generates a boilerplate ansible-navigator.yml config file

### ISSUE THREAD

**Issue by ffirg** [ansible/ansible-navigator#528]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Ability to run something like:
ansible-navigator create-config which creates an ansible-navigator.yml file with all options listed but commented out.
That would be a much easier way to get started customising than having to reach into the docs.

**Comment by cidrblock** [comment]
+1

**Comment by cidrblock** [comment]
Related: https://github.com/ansible/ansible-navigator/issues/577

**Comment by cidrblock** [comment]
Fixed in version 2

ansible-navigator settings --sample
