### ISSUE TITLE
Unable to install ansible-navigator on M1 Mac due to onigurumacffi install failure

### ISSUE THREAD

**Issue by michaelford85** [ansible/ansible-navigator#530]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
`pip install ansible-navigator` fails on the M1 Mac. During the process, the installer tries to run `pip install onigurumacffi`, which results in the following error:

`build/temp.macosx-10.14.6-arm64-3.8/_onigurumacffi.c:569:10: fatal error: 'oniguruma.h' file not found`

Alternatively, I installed oniguruma with homebrew successfully, but running `pip install ansible-navigator` still results in the above error.

##### ANSIBLE-NAVIGATOR VERSION

N/A as ansible-navigator is not installed successfully.

##### CONFIGURATION

N/A as ansible-navigator is not installed successfully.

##### LOG FILE

N/A as ansible-navigator is not installed successfully.

##### STEPS TO REPRODUCE

On any M1 series Mac, run `pip3 install ansible-navigator`, or from within a pip3 virtual environment, run `pip install ansible-navigator`

##### EXPECTED RESULTS

ansible-navigator is installed successfully.

##### ACTUAL RESULTS

Install fails with the following error: `build/temp.macosx-10.14.6-arm64-3.8/_onigurumacffi.c:569:10: fatal error: 'oniguruma.h' file not found`

**Comment by cidrblock** [comment]
@tonykay Thanks for that :)

Did you have to do anything special to get the python dependency `onigurumacffi` installed?  Or did it just get pulled down without issues when `ansible-navigator` was pip installed?

**Comment by ssbarnea** [comment]
I am still waiting for my M1 to arrive but I will likely work on that once I will be affected by it.
