### ISSUE TITLE
ansible.cfg inventory parameter doesn't work, forces you to use -i

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible-navigator#55]
I have this setup

```
[defaults]
inventory = inventory.yaml
```

these two work->
```
ansible-playbook site.yaml
ansible-navigator playbook site.yaml
```

this does not work

```
ansible-navigator explore site.yaml
```
![image](https://user-images.githubusercontent.com/6537680/111524446-ce0cec00-8732-11eb-8d41-d956a4b900f1.png)

**Comment by cidrblock** [comment]
PR #167 and the preceding pr that elimates the .cfg and switchs to a yml file have resolved this
