### ISSUE TITLE
[maintenance] Implement changelog management

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible-navigator#558]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

I haven't found any changelog in the project. So we should probably start having one. Of course, manually editing it is no fun so it'd be nice to integrate some software for automatic log generation out of per-PR collected change notes.
I've got quite a lot of experience with Towncrier which many projects in the ecosystem use. I also have a Sphinx extension for showing a pre-release changelog. We could go with that or discuss other tools if anybody has strong opinions.

###### Why the changelog should be written by humans for humans
* https://keepachangelog.com
* https://changelog.com/podcast/127

###### Git history, although important, (squashed or not) is not the answer
* https://blog.jaraco.com/dont-use-squash-and-merge/

**Comment by relrod** [comment]
My preference here is to use `antsibull-changelog` since ansible-core already uses it and people are already familiar with that workflow (adding in a fragment with each change).

https://github.com/ansible-community/antsibull-changelog/pull/60 allows antsibull-changelog to be used with other projects, so integrating it here should be relatively easy.

**Comment by webknjaz** [comment]
@relrod do you have a Sphinx extension for displaying the unreleased fragments and a GitHub App for checking their presence? My solution with Towncrier has all of this. And I think it's important for the DX. Also, I'm not a huge fan of the whole RST-in-YAML approach.

**Comment by cidrblock** [comment]
I believe this to be complete. Future enhancements to change log generation can be added as new issues as encountered.
