### ISSUE TITLE
Automatically mount ansible_ssh_private_key_file from inventory to the ee

### ISSUE THREAD

**Issue by mnecas** [ansible/ansible-navigator#569]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
When running the playbook from ee with some inventory, the user needs to mount all ssh keys, it would have been easier when he would just provide the inventory and the navigator would automatically mount it to the ee.

**Comment by cidrblock** [comment]
This would require parsing of the inventory, which is not in scope for navigator any time soon.  The keys can be mounted with custom volume mounts into the container using the settings file or CLI params.

Thanks for the suggestion, but this won't be considered anytime soon.
