### ISSUE TITLE
include_role does not make error with `ansible-navigator explore`

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible-navigator#57]
playbook that should fail (the role does not exist)
```
- hosts: all
  gather_facts: true
  tasks:
  - include_role:
      name: brad.foo.ntp
```

failure with normal ansible-playbook site2.yaml
```
TASK [include_role : brad.foo.ntp] ***************************************************************************************************************************************************************************
ERROR! the role 'brad.foo.ntp' was not found in /home/student1/ntp_demo/roles:/home/student1/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/student1/ntp_demo

The error appears to be in '/home/student1/ntp_demo/site2.yaml': line 5, column 13, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - include_role:
      name: brad.foo.ntp
            ^ here
```

with command `ansible-launcher explore site2.yaml -i inventory.yaml`

![image](https://user-images.githubusercontent.com/6537680/111530988-58a51980-873a-11eb-8d26-97c30c8a5fbc.png)

zooming in (`:0`)
![image](https://user-images.githubusercontent.com/6537680/111531010-6064be00-873a-11eb-853d-9390260f3d99.png)

zooming in (`:3`)
![image](https://user-images.githubusercontent.com/6537680/111531043-69558f80-873a-11eb-82d6-7e25254b9281.png)

but it says failed in bottom right?  very weird

**Comment by cidrblock** [comment]
this is an ansible thing, although the task succeeded, ansible throws the error, not as a failed task. When the lower right box say failed, you can `:st` to see the normal output to find these errors
