### ISSUE TITLE
ansible-navigator blocks with --ask-become-pass 

### ISSUE THREAD

**Issue by alinabuzachis** [ansible/ansible-navigator#599]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

I'm trying to run a playbook with some tasks that require privilege escalation. I tried using `--ask-become-pass` flag  with and without using an EE and the behavior is the same. The execution blocks as showed in the screenshot below. I have to force the quit to exit.

##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 1.1.0
```

##### STEPS TO REPRODUCE

This is a command I used giving the behavior described above.
`ansible-navigator run acl.yml --ask-become-pass -m stdout` 

##### ACTUAL RESULTS

![Screenshot from 2021-10-20 10-59-38](https://user-images.githubusercontent.com/49211501/138062478-39571c42-8e84-4f8d-b063-0dc10cbd354a.png)

Similar behavior is verified when `--ask-vault-pass` is used.

**Comment by cidrblock** [comment]
@alinabuzachis Curious if you had a chance to try it with mode stdout and artifact creation disabled.

**Comment by alinabuzachis** [comment]
@cidrblock I just tried and it solves. Thank you!

**Comment by cidrblock** [comment]
@alinabuzachis excellent, thanks for getting back to us
