### ISSUE TITLE
The navigator uses 100% of cpu in stdout mode

### ISSUE THREAD

**Issue by mnecas** [ansible/ansible-navigator#604]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

When running any playbook with a navigator in stdout mode it uses 100% of CPU core.
My playbook
```
- hosts: localhost
  tasks:
    - command: sleep 40
```
command:
`ansible-navigator run ./playbook.yml -m stdout`

And when I check the `htop` it uses 100%.
##### ANSIBLE-NAVIGATOR VERSION

```
ansible-navigator 1.1.0
```

Run on x86_64 centos 8.4.2105 with podman version 3.2.3.

**Comment by ffirg** [comment]
Confirmed issue. I get the same problem on :
ProductName:	macOS
ProductVersion:	11.6
BuildVersion:	20G165
ansible-navigator 1.0.0
Python 3.9.7
