### ISSUE TITLE
Add ability for ansible-navigator to dump a sample settings file to stdout or file

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible-navigator#611]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
The example provided here: https://ansible-navigator.readthedocs.io/en/latest/settings/ is great, however it is coming up in prototype training class for ansible-navigator that its hard (especially in disconnected environments) for folks to get an example right there.  Is there a way to dump a file with every knob so that people can cut and paste (similar to how module documentation does).

e.g. we want this->
https://ansible-navigator.readthedocs.io/en/latest/settings/

somewhere on the linux node where you have installed ansible-navigator to mimic the behavior of the default example /etc/ansible/ansible.cfg

**Comment by jbaresfe** [comment]
I will be indeed very beneficial, so it is out of the box in case of not having access to external network. At the same time, reference files will be up to date with latest changes on the configuration settings.

**Comment by cidrblock** [comment]
+1 for this, it probably won't be installed anywhere but instead ansible-navgiator should have a way to generate one for you as a sample....

**Comment by cidrblock** [comment]
![Screenshot_20211117-142923](https://user-images.githubusercontent.com/18386516/142292795-08a5a89f-7c4d-4b36-a50a-02f0448931b8.png)

The sample in the docs has a copy button now :)

**Comment by cidrblock** [comment]
This will be in the 2.0 release

`ansible-navigator settings --sample`
