### ISSUE TITLE
 Add support for sidecar filter/test plugin doc support

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible-navigator#617]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Currently filter/test plugin doc are not displayed in the navigator UI. As ansible-core will support rendering the plugin docs with PR https://github.com/ansible/ansible/pull/76170 update navigator to support it.

**Comment by cidrblock** [comment]
RElated: https://github.com/ansible/ansible/pull/74963
