### ISSUE TITLE
RFE: subcommand to invoke ansible-vault

### ISSUE THREAD

**Issue by sugitk** [ansible/ansible-navigator#620]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

The customer requests to invoke ansible-vault command with EE.

**Comment by cidrblock** [comment]
@sugitk Ad-hoc command support will be coming soon via https://github.com/ansible/ansible-navigator/pull/624  

let me know fi this might work in this case,

thanks- Brad

**Comment by sugitk** [comment]
@cidrblock
I haven't tested the PR yet though, I guess it will meet the requirement if it is implemented.  Thank you :)

**Comment by cidrblock** [comment]
Related: https://github.com/ansible/ansible-navigator/pull/941
