### ISSUE TITLE
Linters, Type checking and coverage support appear to be missing from CI

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#626]
https://github.com/ansible/ansible-navigator/blob/1e12426013f4e495236116e4f4ee0376332d59b3/.zuul.d/jobs.yaml#L1

A quick look indicates in might be related to the move of zuul config into the repo

**Comment by webknjaz** [comment]
Honestly, I'd rather add them to GHA. I was planning to align a lot of the configuration with the best practices anyway.

**Comment by cidrblock** [comment]
Adding AAP label since this is a prereq for AAP features coming in ove the next couple months

**Comment by ssbarnea** [comment]
Closing it as we already ensured we run linters, unit and since few minutes ago coverage: https://app.codecov.io/gh/ansible/ansible-navigator
