### ISSUE TITLE
Building dev docs for ansible-navigator

### ISSUE THREAD

**Issue by alisonlhart** [ansible/ansible-navigator#628]
##### ISSUE TYPE
 - Doc issue

##### SUMMARY

There are currently no surfaced dev docs for ansible-navigator. Was working with @thedoubl3j on fixing issue #598 and had some trouble with building source and testing. We would like to start building some dev_docs to step through the process for anyone wanting to get started on developing features or bugfixing navigator issues. 

Initial doc suggestions:
- Getting started with developing ansible-navigator - environment set-up with vscode
- Walkthrough/summary of src files
- Overview of base entry points
- Building from src and installing packages for testing
- Testing process and examples

**Comment by thedoubl3j** [comment]
while there is python docs, particularly around setup.py, surfacing as much info as possible to either the docs dir or even just a general dev guide I think will help out a lot for people either looking to hack a little bit on their own install of navigator or those looking to contribute.

**Comment by cidrblock** [comment]
@alisonlhart @thedoubl3j This is a great idea!
