### ISSUE TITLE
Ability to specify the podman --cert-dir option in config

### ISSUE THREAD

**Issue by watsonb** [ansible/ansible-navigator#632]
##### ISSUE TYPE
 - Add ability to specify additional podman command-line options in ansible-navigator.yml

##### SUMMARY
Our corporate environment uses a 3rd party SSL inspection tool that re-signs all traffic with the vendor's root certificate.  This obviously breaks things when trying to pull from, say, quay.io and the cert is signed by someone else.  It appears there is no good way to put the vendor's cert in a standard location that podman will search (e.g., /etc/containers/certs.d) (see https://github.com/containers/podman/issues/2726).  As such, I have to resort to passing the `--certs-dir` option to podman on the command-line each time I need to login to a container registry and pull from it.

However, if you set the pull-policy in your ansible-navigator.yml config, it will fail to pull the image on launch of `ansible-navigator` because it is not passing that `--certs-dir` option.  If podman can search known directories and use the certificates therein, this is a moot point, but I cannot manage to get that working.

**Comment by cidrblock** [comment]
Hey @watsonb ,

Thanks for this.  It's really great to get some real-world use cases.

I can think of 2 ways to handle this...

1) would be for a new setting to be supported, maybe 'pull-parameters', which would be just a string of anything that would be added to the pull command
2) turn the pull command into a setting that was templated with the image name, eg. `{container-engine} pull {image}` would be the default, but you could override it in the settings with `{container-engine} --certs-dir mydir pull {image}`

`container-engine` and `image` would be the only 2 variables available and pull from the other settings.

This would not be very different than they way we handle the `artifact-file`, where the default is `{playbook_dir}/{playbook_name}-artifact-{ts_utc}.json` and the dir/name and ts are variables

let me know if either or both would work, brad

**Comment by watsonb** [comment]
Hello @cidrblock ,

I think either/both of those approaches would work just fine.  Let me know when you need a tester.

**Comment by cidrblock** [comment]
@watsonb Check out #952 , it add a new settings file/CLI/environment variable that will let you add to the pull command that is generated.  LMK

Sorry it took a bit to get to this.

**Comment by watsonb** [comment]
I read through your PR comments and stuff and looks like it should work.  Not sure how to test it locally (I typically `pip install` from PyPi into a virtual env).  Would I just create a new venv and `pip install` from your Git repo?

**Comment by cidrblock** [comment]
I've never claimed to be great at using git,  but I think this should work to checkout the PR:

```
mkdir show
cd show
# build a venv
python3 -m venv venv
# activate the venv
source venv/bin/activate
# clone the naivgator repo
git clone https://github.com/ansible/ansible-navigator.git
# cd into the repo dir
cd ansible-navigator
# add upstream as a remote
git remote add upstream https://github.com/ansible/ansible-navigator.git
# fetch the PR into a new branch called 952
git fetch upstream pull/952/head:952
# checkout that branch
git checkout 952
# back up one directory
cd ..
# install from the repo into the vevn
pip install ./ansible-navigator
# confirm ne parameter is available
ansible-navigator --help | grep pull
  --pa PULL_ARGUMENTS [PULL_ARGUMENTS ...], --pull-arguments PULL_ARGUMENTS [PULL_ARGUMENTS ...]
                        to the pull command when pulling an execution
  --pp PULL_POLICY, --pull-policy PULL_POLICY
                        Specify the image pull policy. always:Always pull the
                        never:Never pull the image, tag:if the image tag is
                        'latest', always pull the image, otherwise pull if not
```

**Comment by watsonb** [comment]
the procedure you outlined above worked for me.  How would you specify these pull arguments in your `ansible-navigator.yml` config file?

**Comment by cidrblock** [comment]
oh, I guess I should have provided that :)

Yeah, I think the settings file is the easiest way:

```yaml
pull-policy: never
pull:
  arguments:
  - "--tls-verify=false"
```

arguments is a list....

I should note, `pull-policy` is going to get moved under `pull` in the future as `policy`, it will be a breaking change and part of the 2.0 release....  It will drive me nuts if it doesn't get moved.
