### ISSUE TITLE
Unignore `F401 module imported but unused` in flake8

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible-navigator#720]
F401 module imported but unused

Since we don't know why it is skipped, and we have no violations, and it _seems_ sane, Should it be enabled, maybe not this PR because I think this is about the format of the file not removals/additions

_Originally posted by @cidrblock in https://github.com/ansible/ansible-navigator/pull/706#discussion_r767148207_

**Comment by cidrblock** [comment]
Fixed with #916
