### ISSUE TITLE
Explain that fixing global flake8 ignores is unnecessary, in the config

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible-navigator#722]
Can we add a note in the global section that:

1) exceptions should be fixed
2) if not, exception is in the file, inline
3) if not possible for some reason, exception can go here, but a majority of these are temporary
4) ACD of global needs team review (not today but in the future)

_Originally posted by @cidrblock in https://github.com/ansible/ansible-navigator/pull/706#discussion_r767149509_

**Comment by cidrblock** [comment]
The flake8 file is now well commented
