### ISSUE TITLE
Disable `wrong-import-order` this rule in pylint when making `isort` required

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible-navigator#784]
This issue has some of the explanation suggesting that pylint uses isort under the hood: https://github.com/PyCQA/pylint/issues/3817#issuecomment-687892090.

And this is what FAQ recommends explicitly too: https://pylint.pycqa.org/en/latest/faq.html#i-am-using-another-popular-linter-alongside-pylint-which-messages-should-i-disable-to-avoid-duplicates.

_Originally posted by @webknjaz in https://github.com/ansible/ansible-navigator/pull/777#r789590734 and https://github.com/ansible/ansible-navigator/pull/777/files#r789596349_

**Comment by cidrblock** [comment]
unassigned self as I do not see an issue here until the sort order for pylint is violated, assigning @webknjaz to close or remediate

**Comment by cidrblock** [comment]
The current configuration of pylint and isort do not conflict.  If this is an issue in the future, it can be addressed with a new issue and PR.

**Comment by webknjaz** [comment]
I think the main motivation was not the conflict resolution but rather performance optimization — less enabled rules usually mean that pylint may end up running a little bit faster. Since we usually raise the question of responsiveness, I imagine that this may be important. Also, having less duplicated output for the same violations from different tools would probably reduce cluttering.
