### ISSUE TITLE
Pare/remove `share` dir

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible-navigator#83]
As we've already encountered, the `share` dir can cause problems during development and packaging. It seems like most of the items there should just be under various datafile subpackages in the main project tree, and the couple of items that we really want to be user-configurable/augmentable should just be loadable from config dirs (which can be located using something akin to what's there now). At first blush, it seems like themes are the only item that currently falls into that category, or am I wrong?

My primary concern is that we don't repeat the mistakes of `/etc/ansible.cfg` and never being able to effectively change or augment defaults by laying down a live all-encompassing config file.

**Comment by webknjaz** [comment]
Related to https://github.com/ansible/ansible-navigator/issues/550?

**Comment by cidrblock** [comment]
This PR demonstrates how to write the image instrospection script to a temp directory and mount that https://github.com/ansible/ansible-navigator/pull/1153
