### ISSUE TITLE
FAQ: Add entry for `/dev/mqueue/`

### ISSUE THREAD

**Issue by cidrblock** [ansible/ansible-navigator#868]
as suggested in #866

**Comment by webknjaz** [comment]
I was thinking more like a `tip` or `note` admonition in the text where WSL2 is explained. Or was it in a separate document? So maybe we'd need two additions to the docs, then.

**Comment by cidrblock** [comment]
Well, it is in the installation docs already for WSL, but the issue pre-dates those docs.

I think an FAQ entry explaining the error and a little more explanation in the install docs would both be good.

**Comment by cidrblock** [comment]
waiting on this: https://github.com/ansible/ansible-runner/issues/984
