### ISSUE TITLE
broken changlog link

### ISSUE THREAD

**Issue by thedoubl3j** [ansible/ansible-navigator#970]
##### ISSUE TYPE
 - Doc issue

##### SUMMARY

https://ansible-navigator.rtfd.io/en/latest/contributing.html#adding-change-notes-with-your-prs does not point to anything. 

Not sure where it lives now but whenever we find it, might want to update the top level CHANGELOG.md with it.

**Comment by webknjaz** [comment]
Not sure where you saw it but feel free to change it to https://ansible-navigator.rtfd.io/en/latest/contributing/guidelines/#adding-change-notes-with-your-prs.
